pages_data = {
    "JBZD": {
        "url": "https://jbzd.com.pl/",
        "img_pattern": {"name": "img", "attrs": {"class": "article-image"}},
        "img_tag": "src",
        "page_direction": "increasing",
        "page_prefix": "str/",
    },
    "kwejk": {
        "url": "https://kwejk.pl/",
        "img_pattern": {"name": "img", "attrs": {"class": "full-image"}},
        "img_tag": "src",
        "page_direction": "decreasing",
        "page_prefix": "strona/",
        "start_from": None,
        "page_pattern": {"name": "li", "attrs": {"class": "current"}},
    },
    "faktopedia": {
        "url": "https://faktopedia.pl/",
        "img_tag": "src",
        "img_prefix": "https://faktopedia.pl",
        "img_pattern": {"name": "img", "attrs": {"class": "pic"}},
        "page_prefix": "page/",
        "page_direction": "increasing",
    },
    "demotywatory": {
        "url": "https://demotywatory.pl/",
        "img_tag": "src",
        "img_pattern": {"name": "img", "attrs": {"class": "demot"}},
        "page_direction": "increasing",
        "page_prefix": "page/",
    },
    "paczaizm": {
        "url": "https://paczaizm.pl/",
        "img_tag": "data-lazy-src",
        "img_pattern": {"name": "img", "attrs": {"class": "wp-post-image"}},
        "page_prefix": "page/",
        "page_direction": "increasing",
    },
    "chamsko": {
        "url": "https://www.chamsko.pl/",
        "img_tag": "src",
        "img_prefix": "https://www.chamsko.pl",
        "img_pattern": {"name": "img", "attrs": {"alt": ""}},
        "page_prefix": "page/",
        "page_direction": "increasing",
    },
}
