pages_data = {
    "JBZD": {
        "url": "https://jbzd.com.pl/",
        "img_pattern": {"name": "img", "attrs": {"class": "article-image"}},
        "img_tag": "src",
        "page_direction": "increasing",
        "page_prefix": "str/",
    },
    "kwejk": {
        "url": "https://kwejk.pl/",
        "img_pattern": {"name": "img", "attrs": {"class": "full-image"}},
        "img_tag": "src",
        "page_direction": "decreasing",
        "page_prefix": "strona/",
        "page_pattern": {"name": "li", "attrs": {"class": "current"}},
    },
    "faktopedia": {
        "url": "https://faktopedia.pl/",
        "img_pattern": {"name": "img", "attrs": {"class": "pic"}},
        "img_tag": "src",
        "page_direction": "increasing",
        "img_prefix": "https://faktopedia.pl",
        "page_prefix": "page/",
    },
    "demotywatory": {
        "url": "https://demotywatory.pl/",
        "img_pattern": {"name": "img", "attrs": {"class": "demot"}},
        "img_tag": "src",
        "page_direction": "increasing",
        "page_prefix": "page/",
    },
    "paczaizm": {
        "url": "https://paczaizm.pl/",
        "img_pattern": {"name": "img", "attrs": {"class": "wp-post-image"}},
        "img_tag": "data-lazy-src",
        "page_direction": "increasing",
        "page_prefix": "page/",
    },
    "chamsko": {
        "url": "https://www.chamsko.pl/",
        "img_pattern": {"name": "img", "attrs": {"alt": ""}},
        "img_tag": "src",
        "page_direction": "increasing",
        "img_prefix": "https://www.chamsko.pl",
        "page_prefix": "page/",
    },
    "pocisk": {
        "url": "https://pocisk.org/",
        "img_pattern": {"name": "img", "attrs": {"class": "wp-post-image"}},
        "img_tag": "data-src",
        "page_direction": "increasing",
        "page_prefix": "page/",
    },
    "wiocha": {
        "url": "https://www.wiocha.pl/",
        "img_pattern": {"name": "img", "attrs": {"class": "imageitself", "title": "", "alt": ""}},
        "img_tag": "src",
        "page_direction": "increasing",
        "page_prefix": "absurdy,",
    },
    "sadistic": {
        "url": "https://www.sadistic.pl/obrazki/",
        "img_pattern": {
            "name": "img",
            "attrs": {"alt": "", "style": "max-width: 775px; display: block; margin: 0 auto"},
        },
        "img_tag": "src",
        "page_direction": "decreasing",
        "page_prefix": "/",
        "page_pattern": {"name": "div", "attrs": {"class": "pagination"}},
    },
}
